version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx2g"
    SPRING_PROFILES_ACTIVE: "prod"  # Altere conforme necessário para o seu perfil

phases:
  install:
    runtime-versions:
      java: corretto24  # Usando o Amazon Corretto 24 como versão do Java
    commands:
      - echo Installing Maven dependencies...
      - mvn -v  # Verificando a versão do Maven
      - mvn install -DskipTests=true  # Instalando as dependências sem rodar os testes

  pre_build:
    commands:
      - mvn clean

  build:
    commands:
      - echo Building the app...
      - mvn package -DskipTests  # Compilando o projeto, sem rodar os testes
      - echo Build done.

  post_build:
    commands:
      - echo Wrapping JAR...
      - ls target/  # Lista o diretório target para verificar o arquivo JAR gerado
      - mv target/*.jar app.jar  # Renomeia o arquivo JAR para app.jar

artifacts:
    files:
      - '**/*'

cache:
  paths:
    - '/root/.m2/**/*'  # Cache das dependências do Maven
